target-version = "py310"

[lint]
exclude = ["docs/*"]
select = ["ALL"]
extend-ignore = [
    "ANN401",
    "COM812",
    "CPY001",   # Requires copyright notice in every file
    "D105",
    "D107",
    "DTZ",
    "EM",
    "ERA001",
    "FBT",
    "FIX002",
    "PLR2004",
    "TD003",
    "TRY003",
]

[lint.pyupgrade]
keep-runtime-typing = true

[lint.per-file-ignores]
"__init__.py" = ["F403", "PLC0414"]
"tests/*" = [
    "ANN",
    "D",        # Forces docstrings and such
    "PLR6301",  # Method could be a function, class method, or static method
    "S101",
    "S311",
]
"tests/pep526_*.py" = ["N802", "N803", "I002"]
"tests/full_examples/cpio_test.py" = ["PLR6301"]
"tests/validators_test.py" = ["PLR6301"]

[lint.isort]
force-single-line = true
known-first-party = ["binobj"]
lines-after-imports = 2
order-by-type = false
required-imports = ["from __future__ import annotations"]

[lint.mccabe]
max-complexity = 9

[lint.flake8-annotations]
mypy-init-return = true

[lint.pydocstyle]
convention = "google"
